### PR TITLE
Preserve errors

### LINKED ISSUE #7: Errors passed as empty objects
[Issuehunt badges](https://issuehunt.io/r/sindresorhus/electron-better-ipc/issues/7)

In answerRenderer and answerMain errors get passed directly to electron ipc, which serializes Errors as plain objects (https://github.com/electron/electron/issues/7956)

I made a patch that uses your serialize-errors library, but didn't create a pull request because I'm not sure my changes to the test fixtures are up to snuff.

patch: https://github.com/lselden/electron-better-ipc/commit/1f3d72ec5eb1e68d47fbc2454a663391d509fcce

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $90.00)

- [issuehunt issuehunt](https://issuehunt.io/u/issuehunt) ($90.00)
### Submitted pull Requests
- [#22 error transmit](https://issuehunt.io/r/sindresorhus/electron-better-ipc/pull/22)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/sindresorhus/electron-better-ipc/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

### PR DESCRIPTION
**Pull request by jackple**
use npm package `serialize-error` for serialize and created a function named `deserializeError` in `util` for deserialize

Fixes #7

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Referenced issues

This pull request has been submitted to:
- [#7: Errors passed as empty objects](https://issuehunt.io/repos/130656750/issues/7)
---

IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

### CODE REVIEW

**Comment by sindresorhus** [comment]
Note:

> Should be done by adding a .deserialize() method to sindresorhus/serialize-error and then use that here.

**Comment by jackple** [comment]
> Note:
> 
> > Should be done by adding a .deserialize() method to sindresorhus/serialize-error and then use that here.

I do not think adding a .deserialize() method is a good idea, because the object prototype can not pass through ipc.
So I just want to add `deserializeError` method, used like `import {serializeError, deserializeError} from '.'`

**Comment by jackple** [comment]
https://github.com/sindresorhus/serialize-error/pull/24

**Comment by sindresorhus** [comment]
Released: https://github.com/sindresorhus/serialize-error/releases/tag/v5.0.0

**Comment by sindresorhus** [comment]
Can you add a test to ensure errors are correctly handled?

**Comment by jackple** [comment]
@sindresorhus sure，I will do it as soon as possible.

**Comment by jackple** [comment]
- Fix `win is not defined`, should be `mainWindow `
- Restore spectron test and name it `test-with-spectron`
- Use `x.includes(':CONSOLE(')` instead of `!/^\[.*:CONSOLE\(\d\)\]/.test(x)`, You can do anything to change it by your way, I just do not know how to fix it! 😄 
- Add error test

**Comment by jackple** [comment]
Is there a plan to merge and publish a new version? If not, I think I have to use a temporary package.

**Comment by sindresorhus** [comment]
Published: https://github.com/sindresorhus/electron-better-ipc/releases/tag/v0.6.0 :)

**Pull request merged**
