### PR TITLE
Add `ipc.callFocusedRenderer` method

### PR DESCRIPTION
**Pull request by oportocala**
Closes https://github.com/sindresorhus/electron-better-ipc/issues/2

### CODE REVIEW

**Comment by oportocala** [comment]
No tests for this but also I could not find tests for the `callRenderer`, only mention is in the fixture

**Comment by sindresorhus** [comment]
This needs a test. You can find the `callRenderer` test here: https://github.com/sindresorhus/electron-better-ipc/blob/master/test/fixture/index.js And the logging is checked here: https://github.com/sindresorhus/electron-better-ipc/blob/master/test/fixture/test.js#L46

**Comment by oportocala** [comment]
Thanks for the review @sindresorhus!
Will add the test.

**Comment by sindresorhus** [comment]
Bump :)

**Comment by oportocala** [comment]
@sindresorhus I've run into a bit of roadblock with the test.

I can't figure out how to get an answer from the renderer inside on `win.on('focus'` handler.
I tried to add a `sleep` timer [here](https://github.com/sindresorhus/electron-better-ipc/blob/8e1a4ddbaf48d9ccb80489d5c0c155fa897d0eed/test/fixture/test.js#L19) thinking it doesn't have time to send a response before the test closes the `Application` inside the test but that didn't work.

I also tried commenting out the application close, `await t.context.app.stop();` but that didn't help either.

Please see https://github.com/sindresorhus/electron-better-ipc/pull/10/commits/8e1a4ddbaf48d9ccb80489d5c0c155fa897d0eed

Thanks!

**Pull request closed without merging**
